"""empty message

Revision ID: 582a59dbebde
Revises: c7d1994f8201
Create Date: 2024-10-07 22:16:08.826868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582a59dbebde'
down_revision = 'c7d1994f8201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_type', sa.String(length=50), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_characters_favorites')
    op.drop_table('user_planets_favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_planets_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], name='user_planets_favorites_planets_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_planets_favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_planets_favorites_pkey')
    )
    op.create_table('user_characters_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('characters_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], name='user_characters_favorites_characters_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_characters_favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_characters_favorites_pkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
